### ISSUE TITLE
Docker pull

### ISSUE THREAD

**Issue by nubonics** [BabakAkbari/Slither.io-AI#1]
Unable to find image 'slitherio:latest' locally
docker: Error response from daemon: pull access denied for slitherio, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.
See 'docker run --help'.

**Comment by BabakAkbari** [comment]
> Unable to find image 'slitherio:latest' locally
> docker: Error response from daemon: pull access denied for slitherio, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.
> See 'docker run --help'.
@nubonics 
Unfortunately the image is not available on Docker Hub right now and you cannot pull it. I strongly recommend you to build the image yourself by simply following the [instructions](https://github.com/BabakAkbari/Slither.io-AI/blob/master/README.md), wish you the best.

**Comment by BabakAkbari** [comment]
@nubonics So I think I should close this issue. If you have any questions, don't hesitate to ask.
Wish you the best.
